spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        # 2. FONDAMENTALE: Forza Hibernate a usare sedapp per la generazione del DDL
        default_schema: sedapp
        # Aiuta a gestire i nomi degli oggetti nello schema specifico
        jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  ssl:
    enabled: false
    # need to add your own domain's certificate
    key-store: ${KEYSTORE_PATH}
    key-store-type: PKCS12
    # need to set environment variable
    key-store-password: ${SSL_KEYSTORE_PASSWORD}



telegram:
  # set your own token
  botUrl: "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
  # set your own bot username (get it from BotFather)
  botName: ${BOT_USERNAME}
